/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/components/**/*.{js,ts,jsx,tsx,scss}',
    './src/layouts/**/*.{js,ts,jsx,tsx}',
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/styles/**/*.scss',
  ],
  theme: {
    screens: {
      sm: '640px',
      md: '768px',
      md_lg: '992px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    colors: ({ colors }) => ({
      inherit: colors.inherit,
      current: colors.current,
      transparent: colors.transparent,
      black: colors.black,
      white: colors.white,
      slate: colors.slate,
      gray: colors.gray,
      zinc: colors.zinc,
      neutral: colors.neutral,
      stone: colors.stone,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
    }),
    // colors: {
    //   ...colors,
    //   primary: "#4dc1f2",
    //   'primary-light': "#CAEFFF",
    //   secondary: "#f1f1f1",
    //   grayText: "#788995",
    //   grayBorder: "#DDE3E8",
    //   black: "#1D2022",
    //   white: colors.white,
    // },
   
    fontSize: {
      xs: ['1.2rem'],
      sm: ['1.4rem'],
      base: ['1.6rem'],
      lg: ['1.8rem'],
      xl: ['2rem'],
      '2xl': ['2.5rem'],
      '3xl': ['3rem'],
      '4xl': ['4rem'],
      '5xl': ['5rem'],
      '6xl': ['6rem'],
      '7xl': ['7rem'],
      '8xl': ['8rem'],
      '9xl': ['9rem'],
    },
    fontWeight: {
      thin: '100',
      extralight: '200',
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
      black: '900',
    },
    extend: {},
  },
  plugins: [
    require("@tailwindcss/forms")
  ],
}
