import type { NextPage } from 'next'
import Head from 'next/head'

import Hero from '@/components/pages/Hero'
import Menu from '@/components/pages/Menu'
import Coffee from '@/components/pages/Coffee'
import Date from '@/components/pages/Date'
import Letter from '@/components/pages/Letter'

import React from 'react'

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Dinner and Coffee ☕</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">

        <Hero />
        <Menu />
        <Coffee />
        <Date />
        <Letter />

      </main>
    </>
  )
}

export default Home
