import type { NextPage } from 'next'
import Head from 'next/head'
import Menu from '@/components/pages/Menu'
import Hero from '@/components/pages/Hero'
import Image from 'next/image'
import Coffee from '@/components/pages/Coffee'

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Dinner and Coffee ☕</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">

        <Hero />
        <Menu />
        <Coffee />

      </main>
    </>
  )
}

export default Home
