import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center" style={{height: "100vh"}}>
        <div className="bg-cyan-400 rounded-lg p-20">
          <h1 className="title font-medium text-xl">Hello word!</h1>
        </div>
      </main>

    </div>
  )
}

export default Home
